version: '3'

volumes:
  ecom:

services:

  user_db:
    image: postgres
    restart: always
    ports:
      - '32700:5432'
    volumes:
      - ecom:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: ecommerce
